stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - echo "Running tests"

deploy:
  stage: deploy
  image: $CI_REGISTRY_IMAGE:latest
  before_script:
    - kubectl config set-cluster my-cluster --server=https://my-k8s-cluster.example.com --insecure-skip-tls-verify=true
    - kubectl config set-context my-context --cluster=my-cluster --user=my-user
    - kubectl config use-context my-context
  script:
    - kubectl apply -f k8s/deployment.yml
    - kubectl apply -f k8s/service.yml
